import { Metadata } from "next";
import { SITE_URL, canonicalFor } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Learn how instudia collects, protects, and securely manages your personal data in compliance with digital privacy and data protection standards.",
  alternates: { canonical: canonicalFor("/privacy-policy") },
  robots: { index: true, follow: true },
  metadataBase: new URL(SITE_URL),
};

const sections = [
  {
    id: "definitions",
    title: "Definitions",
    content: [
      {
        term: "SERVICE",
        def: "The https://www.instudianagaland.com/ website operated by instudia.",
      },
      {
        term: "PERSONAL DATA",
        def: "Data about a living individual who can be identified from those data (or from those and other information in our possession).",
      },
      {
        term: "USAGE DATA",
        def: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g. duration of a page visit).",
      },
      {
        term: "COOKIES",
        def: "Small files stored on your device (computer or mobile device).",
      },
      {
        term: "DATA CONTROLLER",
        def: "The natural or legal person who determines the purposes and manner of processing personal data. For this Privacy Policy, instudia is the Data Controller.",
      },
      {
        term: "DATA PROCESSORS",
        def: "Natural or legal persons who process data on behalf of the Data Controller. instudia may use Service Providers to process your data more effectively.",
      },
      {
        term: "THE USER",
        def: "The individual using the Service — corresponds to the Data Subject.",
      },
    ],
  },
  {
    id: "data-collected",
    title: "Types of Data Collected",
    body: `While using our Service, we may ask you to provide personally identifiable information including: email address, first and last name, phone number, address, city, state, ZIP code, country, cookies, and usage data.

We may also collect Usage Data automatically — including your IP address, browser type and version, pages you visit, time and date of visit, and time spent on those pages.

We use cookies and similar tracking technologies to track activity on our Service. You can instruct your browser to refuse all cookies. The cookies we use include: Session Cookies (to operate our Service), Preference Cookies (to remember your settings), Security Cookies (for security purposes), and Advertising Cookies (to serve relevant ads).`,
  },
  {
    id: "use-of-data",
    title: "Use of Data",
    bullets: [
      "To provide and maintain our Service",
      "To notify you about changes to our Service",
      "To allow you to participate in interactive features",
      "To provide customer support",
      "To gather analytics and improve our Service",
      "To monitor usage of our Service",
      "To detect, prevent, and address technical issues",
      "To fulfil any other purpose for which you provide it",
      "To carry out our obligations and enforce our rights",
      "To provide you with updates, notices, and email-instructions",
      "To provide news, special offers, and general information about related services",
      "For any other purpose with your consent",
    ],
  },
  {
    id: "retention",
    title: "Retention of Data",
    body: `We will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. We will retain and use your data to comply with legal obligations, resolve disputes, and enforce our legal agreements.

Usage Data is generally retained for a shorter period, except when used to strengthen security or improve functionality, or when legally required to retain it longer.`,
  },
  {
    id: "transfer",
    title: "Transfer of Data",
    body: `Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where data protection laws may differ from those in your jurisdiction.

If you are located outside India and choose to provide information to us, please note that we transfer and process the data in India. Your consent to this Privacy Policy followed by your submission of information represents your agreement to that transfer.

instudia will take all steps reasonably necessary to ensure your data is treated securely and in accordance with this Privacy Policy.`,
  },
  {
    id: "service-providers",
    title: "Service Providers",
    body: `We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related activities, or assist us in analysing how our Service is used.

These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

We use third-party providers for: Analytics, CI/CD tools, Behavioral Remarketing, and WhatsApp Business API communication.`,
  },
  {
    id: "whatsapp",
    title: "WhatsApp Communication",
    body: `We use the Meta WhatsApp Business API to communicate with users. We collect phone numbers for the purpose of sending automated messages and updates.

Data collection: We collect and process user phone numbers solely to send WhatsApp messages via the Meta WhatsApp Business API.

Use of Data: Used only for the specific communication purpose you opted into (e.g., updates, notifications). We do not sell or share this data with third parties.

Data Deletion: Users can request data deletion by replying "STOP" or emailing instudia.nagaland@gmail.com. We will remove your data within 48 hours.

Security: We use Meta's official Cloud API, which ensures end-to-end encryption for message content.`,
  },
  {
    id: "changes",
    title: "Changes to This Privacy Policy",
    body: `We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "effective date" at the top.

You are advised to review this Privacy Policy periodically. Changes are effective when posted on this page.`,
  },
  {
    id: "contact",
    title: "Contact Us",
    body: `If you have any questions about this Privacy Policy, please contact us:\n\nEmail: instudia.nagaland@gmail.com\nPhone: +91-8798-587-779\nAddress: First Floor, Vikiye Center, Notun Bosti, Dimapur, Nagaland 797112`,
  },
];

export default function PrivacyPolicyPage() {
  return (
    <main className="bg-white min-h-screen">
      {/* Hero */}
      <section className="relative overflow-hidden border-b border-neutral-100 pt-24 pb-16 px-6">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[250px] bg-brandpurple/5 rounded-full blur-[80px] pointer-events-none" />
        <div className="relative mx-auto max-w-4xl">
          <div className="flex items-center gap-2 mb-4">
            <span className="text-[10px] font-extrabold tracking-[0.2em] text-brandpurple uppercase">
              Legal
            </span>
            <span className="text-neutral-300">/</span>
            <span className="text-[10px] font-semibold text-gray-400 uppercase tracking-widest">
              Privacy Policy
            </span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-black tracking-tight text-[#1B1C1E]">
            Privacy Policy
          </h1>
          <p className="mt-4 text-gray-500 max-w-2xl leading-relaxed">
            This policy explains how instudia collects, uses, and protects your personal data. Please read it carefully before using our services.
          </p>
          <div className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-gray-400 bg-gray-50 border border-neutral-100 rounded-full px-4 py-2">
            <span className="w-1.5 h-1.5 rounded-full bg-flourescent" />
            Effective date: January 1, 2026
          </div>
        </div>
      </section>

      {/* Content */}
      <div className="mx-auto max-w-4xl px-6 py-16">
        <div className="space-y-16">
          {sections.map((section, i) => (
            <section key={section.id} id={section.id} className="scroll-mt-24">
              {/* Section header */}
              <div className="flex items-start gap-4 mb-6">
                <span className="flex-shrink-0 w-8 h-8 rounded-full bg-brandpurple/10 flex items-center justify-center text-xs font-black text-brandpurple mt-0.5">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <h2 className="text-xl sm:text-2xl font-black text-[#1B1C1E]">
                  {section.title}
                </h2>
              </div>

              <div className="pl-12">
                {/* Definitions list */}
                {"content" in section && section.content && (
                  <div className="space-y-4">
                    {section.content.map((item) => (
                      <div
                        key={item.term}
                        className="flex gap-4 p-4 rounded-2xl bg-gray-50 border border-neutral-100"
                      >
                        <span className="flex-shrink-0 text-xs font-extrabold uppercase tracking-widest text-brandpurple mt-0.5 min-w-[9rem]">
                          {item.term}
                        </span>
                        <p className="text-sm text-gray-600 leading-relaxed">{item.def}</p>
                      </div>
                    ))}
                  </div>
                )}

                {/* Bullet list */}
                {"bullets" in section && section.bullets && (
                  <ul className="space-y-2">
                    {section.bullets.map((b, bi) => (
                      <li key={bi} className="flex items-start gap-3 text-sm text-gray-700 leading-relaxed">
                        <span className="flex-shrink-0 w-1.5 h-1.5 rounded-full bg-brandpurple mt-2" />
                        {b}
                      </li>
                    ))}
                  </ul>
                )}

                {/* Body text */}
                {"body" in section && section.body && (
                  <div className="space-y-4">
                    {section.body.split("\n\n").map((para, pi) =>
                      section.id === "contact" && pi === 0 ? (
                        <p key={pi} className="text-sm text-gray-700 leading-relaxed">{para}</p>
                      ) : section.id === "contact" && pi === 1 ? (
                        <div key={pi} className="border border-brandpurple/20 rounded-2xl p-5 bg-brandpurple/5 space-y-1.5">
                          {para.split("\n").map((line, li) => (
                            <p key={li} className="text-sm font-semibold text-[#1B1C1E]">{line}</p>
                          ))}
                        </div>
                      ) : (
                        <p key={pi} className="text-sm text-gray-700 leading-relaxed">{para}</p>
                      )
                    )}
                  </div>
                )}
              </div>

              {i < sections.length - 1 && (
                <div className="mt-16 border-t border-neutral-100" />
              )}
            </section>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-16 rounded-2xl border border-flourescent/30 bg-flourescent/5 px-6 py-5 flex items-start gap-3">
          <span className="text-xl mt-0.5">🔒</span>
          <div>
            <p className="text-sm font-bold text-[#1B1C1E]">Your data is safe with us</p>
            <p className="text-xs text-gray-500 mt-1">
              instudia is committed to protecting your privacy. We never sell your personal data to third parties. For questions, contact{" "}
              <a href="mailto:instudia.nagaland@gmail.com" className="text-brandpurple font-semibold hover:underline">
                instudia.nagaland@gmail.com
              </a>
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
