import {
  CheckCircleIcon,
  InformationCircleIcon,
} from "@heroicons/react/20/solid";

export default function PrivacyPolicy() {
  return (
    <div className="bg-white px-6 py-32 lg:px-8">
      <div className="mx-auto max-w-4xl text-base leading-7 text-gray-700">
        <p className="text-base font-semibold leading-7 text-purple-600">
          Effective date: 2022-10-03
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
          Privacy Policy
        </h1>
        <p className="mt-6 text-xl leading-8">
          instudia ("us", "we", or "our") operates https://instudianagaland.com/
          (hereinafter referred to as "Service"). Our Privacy Policy governs
          your visit to https://instudianagaland.com/, and explains how we
          collect, safeguard and disclose information that results from your use
          of our Service. We use your data to provide and improve Service.
        </p>
        <div className="mt-10 max-w-4xl">
          <p>
            By using Service, you agree to the collection and use of information
            in accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions. Our Terms and Conditions
            ("Terms") govern all use of our Service and together with the
            Privacy Policy constitutes your agreement with us ("agreement").
          </p>
          <ul role="list" className="mt-8 max-w-xl space-y-8 text-gray-600">
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">SERVICE</strong>{" "}
                means the https://instudianagaland.com/ website operated by
                instudia.
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">
                  PERSONAL DATA
                </strong>{" "}
                means data about a living individual who can be identified from
                those data (or from those and other information either in our
                possession or likely to come into our possession).
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">
                  USAGE DATA
                </strong>{" "}
                is data collected automatically either generated by the use of
                Service or from Service infrastructure itself (for example, the
                duration of a page visit).
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">COOKIES</strong>{" "}
                are small files stored on your device (computer or mobile
                device).
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">
                  DATA CONTROLLER
                </strong>{" "}
                means a natural or legal person who (either alone or jointly or
                in common with other persons) determines the purposes for which
                and the manner in which any personal data are, or are to be,
                processed. For the purpose of this Privacy Policy, we are a Data
                Controller of your data.
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">
                  DATA PROCESSORS (OR SERVICE PROVIDERS)
                </strong>{" "}
                means any natural or legal person who processes the data on
                behalf of the Data Controller. We may use the services of
                various Service Providers in order to process your data more
                effectively.
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">
                  THE USER
                </strong>{" "}
                is the individual using our Service. The User corresponds to the
                Data Subject, who is the subject of Personal Data.
              </span>
            </li>
            <li className="flex gap-x-3">
              <CheckCircleIcon
                aria-hidden="true"
                className="mt-1 h-5 w-5 flex-none text-purple-600"
              />
              <span>
                <strong className="font-semibold text-gray-900">
                  DATA SUBJECT
                </strong>{" "}
                is any living individual who is the subject of Personal Data.
              </span>
            </li>
          </ul>
          <p className="mt-8">
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
          <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">
            Types of Data Collected
          </h2>
          <ul className="mt-4">
            <li className="mt-3">
              <p className="text-sm font-semibold text-gray-900">
                Personal Data
              </p>
              <div className="text-sm leading-normal">
                While using our Service, we may ask you to provide us with
                certain personally identifiable information that can be used to
                contact or identify you ("Personal Data"). Personally
                identifiable information may include, but is not limited to:
                <br />
                <ul className="font-semibold text-gray-900">
                  <li>- Email address</li>
                  <li>- First name and last name</li>
                  <li>- Phone number</li>
                  <li>- Address,</li>
                  <li>- Country,</li>
                  <li>- State,</li>
                  <li>- Province,</li>
                  <li>- ZIP/Postal code,</li>
                  <li>- City</li>
                  <li>- Cookies and</li>
                  <li>- Usage Data</li>
                </ul>
                <br />
                We may use your Personal Data to contact you with newsletters,
                marketing or promotional materials and other information that
                may be of interest to you. You may opt out of receiving any, or
                all, of these communications from us by following the
                unsubscribe link.
              </div>
            </li>
            <li className="mt-3">
              <p className="text-sm font-semibold text-gray-900">Usage Data</p>
              <p className="text-sm leading-normal">
                We may also collect information that your browser sends whenever
                you visit our Service or when you access Service by or through
                any device ("Usage Data"). This Usage Data may include
                information such as your computer's Internet Protocol address
                (e.g. IP address), browser type, browser version, the pages of
                our Service that you visit, the time and date of your visit, the
                time spent on those pages, unique device identifiers and other
                diagnostic data. When you access Service with a device, this
                Usage Data may include information such as the type of device
                you use, your device unique ID, the IP address of your device,
                your device operating system, the type of Internet browser you
                use, unique device identifiers and other diagnostic data.
              </p>
            </li>
            <li className="mt-3">
              <p className="text-sm font-semibold text-gray-900">
                Tracking Cookies Data
              </p>
              <div className="text-sm leading-normal">
                We use cookies and similar tracking technologies to track the
                activity on our Service and we hold certain information. Cookies
                are files with a small amount of data which may include an
                anonymous unique identifier. Cookies are sent to your browser
                from a website and stored on your device. Other tracking
                technologies are also used such as beacons, tags and scripts to
                collect and track information and to improve and analyze our
                Service. You can instruct your browser to refuse all cookies or
                to indicate when a cookie is being sent. However, if you do not
                accept cookies, you may not be able to use some portions of our
                Service.
                <figure className="mt-10 border-l border-purple-600 pl-9">
                  <blockquote className="text-gray-900">
                    <div className="mb-2 font-bold">
                      Examples of Cookies we use:
                    </div>
                    <ul>
                      <li>
                        <span className="font-semibold">Session Cookies</span>:
                        We use Session Cookies to operate our Service.
                      </li>
                      <li>
                        <span className="font-semibold">
                          Preference Cookies
                        </span>
                        : We use Preference Cookies to remember your preferences
                        and various settings.
                      </li>
                      <li>
                        <span className="font-semibold">Security Cookies</span>:
                        We use Security Cookies for security purposes.
                      </li>
                      <li>
                        <span className="font-semibold">
                          Advertising Cookies
                        </span>
                        : Advertising Cookies are used to serve you with
                        advertisements that may be relevant to you and your
                        interests.
                        <p className="mt-2 italic">
                          Other Data While using our Service, we may also
                          collect the following information: sex, age, date of
                          birth, place of birth, passport details, citizenship,
                          registration at place of residence and actual address,
                          telephone number (work, mobile), details of documents
                          on education, qualification, professional training,
                          employment agreements, NDA agreements, information on
                          bonuses and compensation, information on marital
                          status, family members, social security (or other
                          taxpayer identification) number, office location and
                          other data.
                        </p>
                      </li>
                    </ul>
                  </blockquote>
                </figure>
              </div>
            </li>
          </ul>
          <div className="mt-16 max-w-4xl">
            <h2 className="text-4xl font-bold tracking-tight text-gray-900">
              Use of Data
            </h2>
            <div className="mt-6">
              instudia uses the collected data for various purposes:
              <ul className="">
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to provide and maintain our Service;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to notify you about changes to our Service;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to allow you to participate in interactive features of our
                  Service when you choose to do so;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to provide customer support;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to gather analysis or valuable information so that we can
                  improve our Service;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to monitor the usage of our Service;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to detect, prevent and address technical issues;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to fulfil any other purpose for which you provide it;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to carry out our obligations and enforce our rights arising
                  from any contracts entered into between you and us, including
                  for billing and collection;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to provide you with notices about your account and/or
                  subscription, including expiration and renewal notices,
                  email-instructions, etc;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  to provide you with news, special offers and general
                  information about other goods, services and events which we
                  offer that are similar to those that you have already
                  purchased or enquired about unless you have opted not to
                  receive such information;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  in any other way we may describe when you provide the
                  information;
                </li>
                <li className="flex gap-x-3">
                  <InformationCircleIcon
                    aria-hidden="true"
                    className="mt-1 h-5 w-5 flex-none text-purple-600"
                  />
                  for any other purpose with your consent.
                </li>
              </ul>
            </div>
            <p className="mt-10">
              <span className="font-semibold">Retention of Data</span>: We will
              retain your Personal Data only for as long as is necessary for the
              purposes set out in this Privacy Policy. We will retain and use
              your Personal Data to the extent necessary to comply with our
              legal obligations (for example, if we are required to retain your
              data to comply with applicable laws), resolve disputes, and
              enforce our legal agreements and policies. We will also retain
              Usage Data for internal analysis purposes. Usage Data is generally
              retained for a shorter period, except when this data is used to
              strengthen the security or to improve the functionality of our
              Service, or we are legally obligated to retain this data for
              longer time periods.
            </p>
          </div>
          <div className="mt-16 max-w-4xl">
            <h2 className="text-4xl font-bold tracking-tight text-gray-900">
              Transfer of Data
            </h2>
            <p className="mt-10">
              Your information, including Personal Data, may be transferred to
              -- and maintained on -- computers located outside of your state,
              province, country or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction.
              If you are located outside India and choose to provide information
              to us, please note that we transfer the data, including Personal
              Data, to India and process it there. Your consent to this Privacy
              Policy followed by your submission of such information represents
              your agreement to that transfer. Instudia will take all the steps
              reasonably necessary to ensure that your data is treated securely
              and in accordance with this Privacy Policy and no transfer of your
              Personal Data will take place to an organisation or a country
              unless there are adequate controls in place including the security
              of your data and other personal information.
            </p>
          </div>
        </div>
        <figure className="mt-10 border-l border-purple-600 pl-9">
          <blockquote className="font-semibold text-gray-900">
            <p className="mt-4 font-thin leading-normal">
              <span className="font-semibold">Service Providers</span>
              <br />
              We may employ third party companies and individuals to facilitate
              our Service ("Service Providers"), provide Service on our behalf,
              perform Service-related services or assist us in analysing how our
              Service is used.
            </p>
            <p className="mt-4 font-thin leading-normal">
              <span className="font-semibold">Analytics</span>
              <br />
              We may use third-party Service Providers to monitor and analyze
              the use of our Service.
            </p>
            <p className="mt-4 font-thin leading-normal">
              <span className="font-semibold">CI/CD tools</span>
              <br />
              We may use third-party Service Providers to automate the
              development process of our Service.
            </p>
            <p className="mt-4 font-thin leading-normal">
              <span className="font-semibold">Behavioral Remarketing</span>
              <br />
              We may use remarketing services to advertise on third party
              websites to you after you visited our Service. We and our
              third-party vendors use cookies to inform, optimise and serve ads
              based on your past visits to our Service.
            </p>
          </blockquote>
        </figure>

        <div className="mt-16 max-w-4xl">
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Changes to This Privacy Policy
          </h2>
          <p className="mt-6">
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update
            "effective date" at the top of this Privacy Policy. You are advised
            to review this Privacy Policy periodically for any changes. Changes
            to this Privacy Policy are effective when they are posted on this
            page.
          </p>
        </div>
        <div className="mt-16 max-w-4xl">
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Contact Us
          </h2>
          <p className="mt-6">
            If you have any questions about this Privacy Policy, please contact
            us by email: instudia.nagaland@gmail.com.
          </p>
        </div>
      </div>
    </div>
  );
}
