import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import PrimaryLayout from "./components/layouts/PrimaryLayout";
import DeviceSizeIndicator from "./components/atom/DeviceSizeIndicator";

const inter = Inter({ subsets: ["latin"] });
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "instudia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <PrimaryLayout>
          <DeviceSizeIndicator />
          {children}
        </PrimaryLayout>
      </body>
    </html>
  );
}
