import React from "react";

export default function ScrollingLogos() {
  return (
    <div
      x-data="{}"
      x-init="$nextTick(() => {
                        let ul = $refs.logos;
                        ul.insertAdjacentHTML('afterend', ul.outerHTML);
                        ul.nextSibling.setAttribute('aria-hidden', 'true');
                    })"
      className="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_128px,_black_calc(100%-128px),transparent_100%)] my-6"
    >
      <ul
        x-ref="logos"
        className="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll"
      >
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.1/landing-page/course-logos/Microsoft_Office_Word_Logo.svg?updatedAt=1740035646100"
            alt="Microsoft Office"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.1/landing-page/course-logos/Microsoft_Office_Excel_Logo.svg?updatedAt=1740035641169"
            alt="Microsoft Excel"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.1/landing-page/course-logos/Microsoft_Office_PowerPoint.svg?updatedAt=1740035646062"
            alt="Microsoft Powerpoint"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/html.svg?updatedAt=1740035638533"
            alt="HTML5"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/css.svg?updatedAt=1740035638469"
            alt="CSS3"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/JavaScript.svg?updatedAt=1740035639051"
            alt="Javascript"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Python.svg?updatedAt=1740035646577"
            alt="Python"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/NodeJs.svg?updatedAt=1740035495089"
            alt="NodeJs"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/React.svg?updatedAt=1740035646079"
            alt="React"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Git.svg?updatedAt=1740035638571"
            alt="Git"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Sass.svg?updatedAt=1740035646471"
            alt="Sass"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-200/landing-page/course-logos/tally-logo.svg?updatedAt=1740035646877"
            alt="Tally"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Figma.svg?updatedAt=1740035639111"
            alt="Figma"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/flask-original.svg?updatedAt=1740035634355"
            alt="Flask"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/numpy-original.svg?updatedAt=1740035634328"
            alt="Numpy"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/pandas-original-wordmark.svg?updatedAt=1740035634261"
            alt="Pandas"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/jupyter-original-wordmark.svg?updatedAt=1740035634519"
            alt="Jupyter"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/django-plain.svg?updatedAt=1740035634151"
            alt="Django"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/docker-original.svg?updatedAt=1740035634402"
            alt="Docker"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/graphql-plain.svg?updatedAt=1740035634342"
            alt="GraphQL"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/nextjs-original.svg?updatedAt=1740035634166"
            alt="NextJS"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Illustrator.svg?updatedAt=1740035638602"
            alt=""
          />
        </li>
      </ul>

      <ul
        aria-hidden="true"
        x-ref="logos"
        className="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll"
      >
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.1/landing-page/course-logos/Microsoft_Office_Word_Logo.svg?updatedAt=1740035646100"
            alt="Microsoft Office"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.1/landing-page/course-logos/Microsoft_Office_Excel_Logo.svg?updatedAt=1740035641169"
            alt="Microsoft Excel"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.1/landing-page/course-logos/Microsoft_Office_PowerPoint.svg?updatedAt=1740035646062"
            alt="Microsoft Powerpoint"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/html.svg?updatedAt=1740035638533"
            alt="HTML5"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/css.svg?updatedAt=1740035638469"
            alt="CSS3"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/JavaScript.svg?updatedAt=1740035639051"
            alt="Javascript"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Python.svg?updatedAt=1740035646577"
            alt="Python"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/NodeJs.svg?updatedAt=1740035495089"
            alt="NodeJs"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/React.svg?updatedAt=1740035646079"
            alt="React"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Git.svg?updatedAt=1740035638571"
            alt="Git"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Sass.svg?updatedAt=1740035646471"
            alt="Sass"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-200/landing-page/course-logos/tally-logo.svg?updatedAt=1740035646877"
            alt="Tally"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Figma.svg?updatedAt=1740035639111"
            alt="Figma"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/flask-original.svg?updatedAt=1740035634355"
            alt="Flask"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/numpy-original.svg?updatedAt=1740035634328"
            alt="Numpy"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/pandas-original-wordmark.svg?updatedAt=1740035634261"
            alt="Pandas"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/jupyter-original-wordmark.svg?updatedAt=1740035634519"
            alt="Jupyter"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/django-plain.svg?updatedAt=1740035634151"
            alt="Django"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/docker-original.svg?updatedAt=1740035634402"
            alt="Docker"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/graphql-plain.svg?updatedAt=1740035634342"
            alt="GraphQL"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/nextjs-original.svg?updatedAt=1740035634166"
            alt="NextJS"
          />
        </li>
        <li>
          <img
            src="https://ik.imagekit.io/dxffek9yf/tr:f-png,w-0.5/landing-page/course-logos/Illustrator.svg?updatedAt=1740035638602"
            alt=""
          />
        </li>
      </ul>
    </div>
  );
}
